#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

/*
 * do not edit this file
 */

int main(int argc, char *argv[])
{
  FILE *infile;
  FILE *outfile;

  if (argc != 3) {
    fprintf(stderr, "Useage: makebin input_file_of_hex_numbers output_bin_file\n");
    return EXIT_FAILURE;
  }

  if ((infile = fopen(argv[1], "r")) == NULL) {
    perror("makebin input file fopen()");
    return EXIT_FAILURE;
  }

  if ((outfile = fopen(argv[2], "w")) == NULL) {
    perror("makebin output file fopen()");
    (void)fclose(infile);
    return EXIT_FAILURE;
  }

  unsigned char ubyte;

  while (fscanf(infile, "%hhx", &ubyte) > 0) {
    printf("got %x\n", ubyte);
    fflush(stdout);
    fwrite(&ubyte, sizeof(ubyte), 1, outfile);
  }

  fclose(infile);
  fclose(outfile);
  return EXIT_SUCCESS;
}
